version: "3.8"
services:
  frontend:
    build: "./frontend"
    ports:
      - "3000:3000"
    volumes:
      - "/frontend/node_modules"
      - "./frontend:/app"
    environment:
      - CHOKIDAR_USEPOLLING=true
  backend:
    build: "./backend"
    ports:
      - "8000:8000"
    volumes:
      - "/backend/node_modules" 
      - "./backend:/app"
  redis:
    image: "redis:alpine"