version: "3.8"
services:
  frontend:
    build: "./frontend"
    ports:
      - "3000:3000"
    volumes:
      - "./frontend:/app:rw"
    environment: 
      - "CHOKIDAR_USE_POLLING=true"
  backend:
    build: "./backend"
    ports:
      - "8000:8000"
    volumes:
      - "/app/node_modules"
      - "./backend:/app:rw"
  redis:
    image: "redis:alpine"