version: "1.0"
services:
  frontend:
    build: "./frontend"
    ports:
      - "8000:8000"
    volumes:
      - "./backend:/app"
  backend:
    build: "./backend"
    ports:
      - "3000:3000"
    volumes:
      - "./frontend:/app"
  redis:
    image: "redis:alpine"